/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/
import { useGLTF } from '@react-three/drei';
import { a } from '@react-spring/three';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

import skyScene from '../assets/3d/need_some_space.glb';

export default function Sky({ isRotating = false, rotationSpeed = 0.15, idleSpeed = 0.02, ...props }) {
  const { nodes, materials } = useGLTF(skyScene);
  const skyRef = useRef();

  useFrame((_, delta) => {
    if (!skyRef.current) return;

    const speed = isRotating ? rotationSpeed : idleSpeed;
    skyRef.current.rotation.y += speed * delta;
  });

  return (
    <a.group {...props} ref={skyRef}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </a.group>
    // <mesh ref={skyRef}> 
    //   <primitive object={sky.scene} />
    // </mesh>
  )
}
